global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  # Redis Master metrics
  - job_name: "redis-master"
    static_configs:
      - targets: ["redis-exporter-master:9121"]
    scrape_interval: 10s
    metrics_path: /metrics

  # Redis Replica 1 metrics
  - job_name: "redis-replica-1"
    static_configs:
      - targets: ["redis-exporter-replica-1:9121"]
    scrape_interval: 10s
    metrics_path: /metrics

  # Redis Replica 2 metrics
  - job_name: "redis-replica-2"
    static_configs:
      - targets: ["redis-exporter-replica-2:9121"]
    scrape_interval: 10s
    metrics_path: /metrics
